/**
 * `gen e2e <Resource>` — the ship gate.
 *
 * Not a scaffolder in the sense the other generators are: it writes one
 * Playwright spec for the happy CRUD path against the `--ui` pages, then
 * runs the full `/check-invariants` suite (`.claude/commands/check-invariants.md`),
 * including `pytest` — this is deliberately the one generator that needs a
 * live database, unlike the DB-free gates `gen resource`/`gen job` run.
 * "Is this slice actually done" is answered here, once, at the end — not
 * scattered across a command file that could disagree with the code that
 * runs it.
 *
 * Deliberately not part of `--ui`: a `test.skip`'d spec that ships is a
 * test that never runs, so this only exists as its own explicit step.
 *
 * The spec assumes the page contract `templates/ui/` is responsible for:
 * a "New <Resource>" link on the list page, a form field per resource
 * field labelled with the field's name, a "Save"/"Create" submit button,
 * and a "Delete" action on the detail page. If those templates end up
 * shaped differently, this generator's selectors are the contract to
 * update, not the pages.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";

import { displayField, parseFields } from "../fields.js";
import type { Field } from "../fields.js";
import type { Names } from "../naming.js";
import { namesFor } from "../naming.js";
import { Plan, reportPlan } from "../plan.js";
import type { Repo } from "../repo.js";
import { loadRepo, rel } from "../repo.js";
import { reportGates, runDbFreeGates, type GateResult } from "../verify.js";

export interface E2eOptions {
  name: string;
  fields?: string;
  dryRun: boolean;
  force: boolean;
}

export class GeneratorError extends Error {}

export const DEFAULT_DISPLAY_FIELD: Field = { name: "name", kind: "str", optional: false };

function sampleFormValue(field: Field): string {
  return `Test ${field.name} ${Date.now()}`;
}

export function renderSpec(names: Names, display: Field): string {
  const sample = sampleFormValue(display);
  const updated = `${sample} (updated)`;
  const label = display.name;

  return `import { expect, test } from "@playwright/test";

/**
 * Generated by \`pnpm gen e2e ${names.Resource}\` (docs/plans/phase-19.md
 * 19.B). The happy CRUD path only — this is a ship gate, not a coverage
 * suite. Assumes an authenticated organisation context; adjust the
 * sign-in/organisation setup below to match how this project's other e2e
 * specs (see apps/web/e2e/org-permissions.spec.ts) establish one, since
 * that plumbing is project-specific and this generator does not own it.
 */

const API = process.env.E2E_API_URL ?? "http://localhost:8000";

test.describe("${names.Resource} — CRUD", () => {
  test("create, view, edit and delete a ${names.resource} through the UI", async ({ page, request }) => {
    // TODO: authenticate \`page\` and \`request\` against an organisation the
    // way apps/web/e2e/org-permissions.spec.ts does, then set \`orgSlug\`.
    const orgSlug = process.env.E2E_ORG_SLUG;
    test.skip(!orgSlug, "set E2E_ORG_SLUG (or wire real auth setup) to run this spec");

    await page.goto(\`/app/\${orgSlug}/${names.app}\`);
    await page.getByRole("link", { name: /new ${names.resource}/i }).click();

    await page.getByLabel(new RegExp("${label}", "i")).fill("${sample}");
    await page.getByRole("button", { name: /^(create|save)/i }).click();

    await expect(page.getByText("${sample}")).toBeVisible();

    await page.getByText("${sample}").click();
    await page.getByRole("button", { name: /^edit/i }).click();
    await page.getByLabel(new RegExp("${label}", "i")).fill("${updated}");
    await page.getByRole("button", { name: /^save/i }).click();

    await expect(page.getByText("${updated}")).toBeVisible();

    await page.getByRole("button", { name: /^delete/i }).click();
    await page.getByRole("button", { name: /^confirm/i }).click();

    await expect(page.getByText("${updated}")).toHaveCount(0);

    // Server-side proof, not just "the button disappeared": the row is
    // actually gone from the API, the same discipline
    // org-permissions.spec.ts uses for permission enforcement.
    const listResponse = await request.get(\`\${API}/api/v1/orgs/\${orgSlug}/${names.resources}/\`);
    expect(listResponse.ok()).toBe(true);
    const body = await listResponse.json();
    const stillThere = (body.results ?? body).some((row: Record<string, unknown>) =>
      Object.values(row).includes("${updated}"),
    );
    expect(stillThere).toBe(false);
  });
});
`;
}

function runCmd(
  cwd: string,
  name: string,
  invariant: string,
  cmd: string,
  args: string[],
): GateResult {
  // `shell: true` only for `pnpm` on Windows, same as sync-client.ts's
  // steps() — `pnpm` resolves to a .cmd/.ps1 shim there, which
  // child_process can only launch through a shell, and `uv` is a real
  // executable that must NOT go through one (format.ts documents why: a
  // space in the repo path breaks shell re-tokenization on Windows).
  const shell = cmd === "pnpm" && process.platform === "win32";
  const result = spawnSync(cmd, args, { cwd, encoding: "utf8", shell });
  const ok = result.status === 0 && !result.error;
  const output = result.error
    ? `could not run "${cmd} ${args.join(" ")}": ${result.error.message}`
    : `${result.stdout ?? ""}${result.stderr ?? ""}`.trim();
  return { name: `${invariant} — ${name}`, command: `${cmd} ${args.join(" ")}`, ok, output };
}

/**
 * The rest of `/check-invariants` that `runDbFreeGates` doesn't cover:
 * everything that needs a live database, plus the full lint pass. Mirrors
 * `.claude/commands/check-invariants.md` steps 4, 5 and 7 in order.
 * Client drift (step 6) is deliberately not run here — it mutates
 * `packages/api-client/src/generated`, which only one worktree at a time
 * may regenerate (ADR 0004's scope boundary), and this generator has no
 * way to know whether this worktree is the one holding that lock.
 */
function runShipOnlyGates(repo: Repo): GateResult[] {
  const gates: GateResult[] = [];

  gates.push(
    runCmd(repo.apiDir, "tenant-scoping meta-tests", "invariant 6", "uv", [
      "run",
      "pytest",
      "keel/organizations/tests/test_meta_router_wiring.py",
      // Not "test_tenant_isolation.py" — that's what
      // .claude/commands/check-invariants.md still says, but the DRF ->
      // Ninja migration (ADR 0001) renamed the file and the command
      // wasn't updated to match.
      "keel/organizations/tests/test_ninja_tenant_isolation.py",
      "keel/organizations/tests/test_meta_guard_coverage.py",
      "-v",
    ]),
  );

  gates.push(runCmd(repo.apiDir, "full pytest", "invariant 7", "uv", ["run", "pytest"]));
  gates.push(
    runCmd(repo.apiDir, "coverage floors", "invariant 7", "uv", [
      "run",
      "python",
      "../../scripts/check_coverage.py",
    ]),
  );

  gates.push(
    runCmd(repo.apiDir, "ruff check", "full lint pass", "uv", ["run", "ruff", "check", "."]),
  );
  gates.push(
    runCmd(repo.apiDir, "ruff format --check", "full lint pass", "uv", [
      "run",
      "ruff",
      "format",
      "--check",
      ".",
    ]),
  );
  gates.push(runCmd(repo.apiDir, "mypy", "full lint pass", "uv", ["run", "mypy", "."]));
  gates.push(runCmd(repo.root, "web lint", "full lint pass", "pnpm", ["--filter", "web", "lint"]));
  gates.push(
    runCmd(repo.root, "prettier --check", "full lint pass", "pnpm", [
      "exec",
      "prettier",
      "--check",
      ".",
    ]),
  );

  return gates;
}

export function generateE2e(options: E2eOptions): number {
  const repo = loadRepo();
  const names = namesFor(options.name);
  const fields = parseFields(options.fields);
  const display = displayField(fields) ?? DEFAULT_DISPLAY_FIELD;

  const specPath = path.join(repo.root, "apps", "web", "e2e", `${names.resources}.spec.ts`);

  if (fs.existsSync(specPath) && !options.force) {
    throw new GeneratorError(
      `${rel(repo, specPath)} already exists. Pass --force to overwrite it. Nothing was written.`,
    );
  }

  const plan = new Plan();
  plan.add(specPath, renderSpec(names, display));

  if (options.dryRun) {
    reportPlan(repo, plan, true);
    console.log("\n--dry-run: nothing was written, and the gate suite was not run.");
    return 0;
  }

  plan.write();
  reportPlan(repo, plan, false);
  plan.note("");
  console.log(
    `\nNext, and not done for you:\n` +
      `  - wire real authentication/organisation setup into ${rel(repo, specPath)} (the ` +
      `generated spec skips itself until E2E_ORG_SLUG is set — see ` +
      `apps/web/e2e/org-permissions.spec.ts for the sign-up/verify/create-org pattern)\n` +
      `  - once wired, run it: \`pnpm --filter web exec playwright test ${path.basename(specPath)}\`\n` +
      `  - confirm the selectors match what \`--ui\` actually generated; this spec is a` +
      ` contract on the page shape, not a guarantee of it.`,
  );

  console.log(`\nRunning the ship gate — the full /check-invariants suite:`);
  const gates = [...runDbFreeGates(repo), ...runShipOnlyGates(repo)];
  return reportGates(gates) ? 0 : 1;
}
