# Generated by Django 6.1 on 2026-08-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditledgerentry',
            options={'verbose_name_plural': 'Credit ledger entries'},
        ),
    ]
