# Generated by Django 6.1 on 2026-08-27 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_creditledgerentry_options'),
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_updated_at',
            field=models.DateTimeField(blank=True, help_text="The originating Stripe event's `created` timestamp — an LWW version guard. A webhook write only applies when its event is newer than the one that wrote this row last, so an out-of-order redelivery can't resurrect a stale status.", null=True),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='creditledgerentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='creditbalance',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='creditbalance_balance_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='creditledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('hold', 'consume')), ('amount__lt', 0)), models.Q(('kind__in', ('grant', 'release', 'refund')), ('amount__gt', 0)), models.Q(('kind', 'adjustment'), models.Q(('amount', 0), _negated=True)), _connector='OR'), name='creditledgerentry_kind_amount_sign'),
        ),
    ]
