"use client";

import { applyFieldErrors } from "@/lib/api/form-error-mapper";
import { useOrgContext } from "@/lib/org/org-context";
import { create__Resource__ } from "@/lib/__resources__/api";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  FormField,
  // keel:if has_text
  FormTextarea,
  // keel:endif
  PageHeader,
  ResourceForm,
} from "@keel/ui";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

// keel:insert choice_field_imports

const __resource__FormSchema = z.object({
  // keel:insert zod_shape
});
type __Resource__FormValues = z.infer<typeof __resource__FormSchema>;

/** `/[org]/__resources__/new` — generated by
 * `pnpm gen resource __Resource__ --ui`. */
export default function New__Resource__Page() {
  const router = useRouter();
  const { currentOrg } = useOrgContext();
  const [formError, setFormError] = useState<string | null>(null);
  const {
    // keel:if has_choice
    control,
    // keel:endif
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<__Resource__FormValues>({ resolver: zodResolver(__resource__FormSchema) });

  if (!currentOrg) return null;

  async function onSubmit(values: __Resource__FormValues) {
    setFormError(null);
    try {
      const __resource__ = await create__Resource__(currentOrg!.slug, values);
      toast.success("__Resource__ created");
      router.push(`/${currentOrg!.slug}/__resources__/${__resource__.id}`);
    } catch (error) {
      setFormError(applyFieldErrors(error, setError));
    }
  }

  return (
    <div className="max-w-lg">
      <PageHeader
        breadcrumb={
          <Breadcrumb>
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink asChild>
                  <Link href={`/${currentOrg.slug}/__resources__`}>__Resources__</Link>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage>New __resource__</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        }
        title="New __resource__"
      />
      <ResourceForm
        onSubmit={handleSubmit(onSubmit)}
        formError={formError}
        submitLabel="Create __resource__"
        submittingLabel="Creating…"
        isSubmitting={isSubmitting}
        onCancel={() => router.push(`/${currentOrg!.slug}/__resources__`)}
      >
        {/* keel:insert form_fields */}
      </ResourceForm>
    </div>
  );
}
