"use client";

import { Can } from "@/components/org/can";
import { applyFieldErrors } from "@/lib/api/form-error-mapper";
import { useOrgContext } from "@/lib/org/org-context";
import { Perm } from "@/lib/org/permissions";
import { deleteWidget, getWidget, updateWidget } from "@/lib/widgets/api";
import { zodResolver } from "@hookform/resolvers/zod";
import type { WidgetOut } from "@keel/api-client";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  Button,
  FormField,
  FormTextarea,
  PageHeader,
  ResourceForm,
} from "@keel/ui";
import { Trash2 } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

import { WidgetStatusField } from "../_components/widget-status-field";
import { WidgetFormSkeleton } from "../_components/widget-form-skeleton";

const widgetFormSchema = z.object({
  name: z.string().min(1, "Name is required.").max(255),
  description: z.string().optional(),
  status: z.string().optional(),
});
type WidgetFormValues = z.infer<typeof widgetFormSchema>;

/** `/[org]/widgets/[id]` — generated by `pnpm gen resource Widget --ui`. */
export default function WidgetDetailPage() {
  const router = useRouter();
  const params = useParams<{ org: string; id: string }>();
  const { currentOrg } = useOrgContext();
  const [widget, setWidget] = useState<WidgetOut | null>(null);
  const [notFound, setNotFound] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const {
    control,
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<WidgetFormValues>({
    resolver: zodResolver(widgetFormSchema),
    values: widget
      ? {
          name: widget.name ?? "",
          description: widget.description ?? "",
          status: widget.status ?? "",
        }
      : undefined,
  });

  useEffect(() => {
    if (!currentOrg) return;
    let cancelled = false;
    getWidget(currentOrg.slug, params.id)
      .then((result) => {
        if (!cancelled) setWidget(result);
      })
      .catch(() => {
        if (!cancelled) setNotFound(true);
      });
    return () => {
      cancelled = true;
    };
  }, [currentOrg, params.id]);

  if (!currentOrg) return null;

  const deletePerm = Perm.WIDGETS_MANAGE;
  const displayValue = widget ? widget.name : params.id;

  const breadcrumb = (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink asChild>
            <Link href={`/${currentOrg.slug}/widgets`}>Widgets</Link>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage>{widget ? displayValue : "…"}</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  );

  if (notFound) {
    return (
      <div>
        <PageHeader breadcrumb={breadcrumb} title="Widget not found" />
        <div className="rounded-lg border border-border p-6">
          <p className="text-sm text-muted-foreground">
            It doesn&apos;t exist, or it belongs to a different organisation.
          </p>
        </div>
      </div>
    );
  }

  if (!widget) {
    return (
      <div className="max-w-lg">
        <PageHeader breadcrumb={breadcrumb} title="…" />
        <WidgetFormSkeleton />
      </div>
    );
  }

  async function onSubmit(values: WidgetFormValues) {
    setFormError(null);
    try {
      const updated = await updateWidget(currentOrg!.slug, params.id, values);
      setWidget(updated);
      toast.success("Widget saved");
    } catch (error) {
      setFormError(applyFieldErrors(error, setError));
    }
  }

  async function onConfirmDelete() {
    await deleteWidget(currentOrg!.slug, params.id);
    setDeleteOpen(false);
    toast.success(`${displayValue} deleted`);
    router.push(`/${currentOrg!.slug}/widgets`);
  }

  return (
    <div className="max-w-lg">
      <PageHeader
        breadcrumb={breadcrumb}
        title={displayValue}
        actions={
          <Can code={deletePerm}>
            <Button variant="outline" onClick={() => setDeleteOpen(true)}>
              <Trash2 />
              Delete
            </Button>
          </Can>
        }
      />
      <ResourceForm
        onSubmit={handleSubmit(onSubmit)}
        formError={formError}
        submitLabel="Save changes"
        submittingLabel="Saving…"
        isSubmitting={isSubmitting}
      >
        <FormField label="Name" id="name" error={errors.name?.message} {...register("name")} />
        <FormTextarea
          label="Description"
          id="description"
          error={errors.description?.message}
          {...register("description")}
        />
        <WidgetStatusField control={control} error={errors.status} />
      </ResourceForm>

      <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {displayValue}?</AlertDialogTitle>
            <AlertDialogDescription>
              This cannot be undone. The widget will be permanently removed.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => void onConfirmDelete()}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
