# Generated by Django 6.1 on 2026-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='', max_length=32),
        ),
    ]
