# Generated by Django 6.1 on 2026-08-25 09:37

import django.contrib.postgres.fields
import django.db.models.deletion
import keel.core.ids
import keel.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', keel.core.models.UUIDv7PrimaryKeyField(default=keel.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('external_account', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reauth_required', 'Re-authorisation required'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='connections_organiz_a14740_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'external_account'), name='unique_org_provider_account')],
            },
        ),
    ]
