# Generated by Django 6.1 on 2026-08-25 09:37

import django.db.models.deletion
import keel.core.ids
import keel.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', keel.core.models.UUIDv7PrimaryKeyField(default=keel.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redriven_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', keel.core.models.UUIDv7PrimaryKeyField(default=keel.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('params', models.JSONField(default=dict)),
                ('result_ref', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', keel.core.models.UUIDv7PrimaryKeyField(default=keel.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ordinal', models.IntegerField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('output_ref', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'created_at'], name='jobs_job_organiz_5519d5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'status'], name='jobs_job_organiz_01f5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstep',
            index=models.Index(fields=['job', 'ordinal'], name='jobs_jobste_job_id_d475e9_idx'),
        ),
    ]
