# Generated by Django 6.1 on 2026-08-27 22:17

import django.db.models.deletion
import keel.core.ids
import keel.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobArtifact',
            fields=[
                ('id', keel.core.models.UUIDv7PrimaryKeyField(default=keel.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produced_by_input_ref', models.CharField(blank=True, default='', help_text="Opaque description of the specific input this row was derived from (a source row's id, a file key, a params field) — free-form because what counts as 'the input' is a consumer decision, not this mixin's.", max_length=255)),
                ('kind', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='jobstep',
            name='jobs_jobste_job_id_d475e9_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='step_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'idempotency_key'), name='unique_org_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='jobstep',
            constraint=models.UniqueConstraint(fields=('job', 'ordinal'), name='unique_job_step_ordinal'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='produced_by_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.job'),
        ),
    ]
