"use client";

import { Can } from "@/components/org/can";
import { useOrgContext } from "@/lib/org/org-context";
import { Perm } from "@/lib/org/permissions";
import { delete__Resource__, list__Resources__ } from "@/lib/__resources__/api";
import type { __Resource__Out } from "@keel/api-client";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  // keel:if has_choice
  Badge,
  // keel:endif
  Button,
  type ColumnDef,
  DataTable,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  EmptyState,
  PageHeader,
} from "@keel/ui";
import { Box, MoreHorizontal, Pencil, Trash2 } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

// keel:insert choice_label_imports
import { __Resources__TableSkeleton } from "./_components/__resources__-table-skeleton";

function cursorFromUrl(url: string | null | undefined): string | undefined {
  if (!url) return undefined;
  return new URL(url).searchParams.get("cursor") ?? undefined;
}

/** `/[org]/__resources__` — generated by `pnpm gen resource __Resource__ --ui`
 * (docs/plans/phase-19.md 19.C). The canonical `<DataTable>` usage: cursor
 * pagination (never offset — the API's `next`/`previous` are opaque URLs),
 * row selection with a permission-gated bulk action, and an empty state
 * with a primary action. */
export default function __Resources__Page() {
  const { currentOrg } = useOrgContext();
  const [__resources__, set__Resources__] = useState<__Resource__Out[]>([]);
  const [cursor, setCursor] = useState<string | undefined>(undefined);
  const [history, setHistory] = useState<(string | undefined)[]>([]);
  const [next, setNext] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [rowPendingDelete, setRowPendingDelete] = useState<__Resource__Out | null>(null);
  const [bulkPendingDelete, setBulkPendingDelete] = useState<{
    ids: string[];
    clearSelection: () => void;
  } | null>(null);

  const load = useCallback(
    async (targetCursor: string | undefined) => {
      if (!currentOrg) return;
      setLoading(true);
      const page = await list__Resources__(currentOrg.slug, { cursor: targetCursor });
      set__Resources__(page.results);
      setNext(page.next ?? null);
      setLoading(false);
    },
    [currentOrg],
  );

  useEffect(() => {
    void load(cursor);
  }, [currentOrg, cursor, load]);

  // keel:if crud_permissions
  const canManage = currentOrg?.permissions.includes(Perm.__RESOURCE___UPDATE) ?? false;
  // keel:endif
  // keel:if manage_permissions
  const canManage = currentOrg?.permissions.includes(Perm.__RESOURCES___MANAGE) ?? false;
  // keel:endif
  // keel:if crud_permissions
  const createPerm = Perm.__RESOURCE___CREATE;
  // keel:endif
  // keel:if manage_permissions
  const createPerm = Perm.__RESOURCES___MANAGE;
  // keel:endif

  const columns = useMemo<ColumnDef<__Resource__Out, unknown>[]>(
    () => [
      // keel:insert columns
      ...(canManage
        ? [
            {
              id: "actions",
              header: "",
              enableHiding: false,
              cell: ({ row }: { row: { original: __Resource__Out } }) => (
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon" className="size-8">
                      <MoreHorizontal />
                      <span className="sr-only">Open actions</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem asChild>
                      <Link href={`/${currentOrg?.slug}/__resources__/${row.original.id}`}>
                        <Pencil />
                        Edit
                      </Link>
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      variant="destructive"
                      onSelect={() => setRowPendingDelete(row.original)}
                    >
                      <Trash2 />
                      Delete
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              ),
            } satisfies ColumnDef<__Resource__Out, unknown>,
          ]
        : []),
    ],
    [currentOrg?.slug, canManage],
  );

  if (!currentOrg) return null;

  async function onConfirmRowDelete() {
    if (!rowPendingDelete) return;
    const row = rowPendingDelete;
    await delete__Resource__(currentOrg!.slug, row.id);
    setRowPendingDelete(null);
    // keel:insert row_delete_toast
    await load(cursor);
  }

  async function onConfirmBulkDelete() {
    if (!bulkPendingDelete) return;
    const { ids, clearSelection } = bulkPendingDelete;
    await Promise.all(ids.map((id) => delete__Resource__(currentOrg!.slug, id)));
    setBulkPendingDelete(null);
    clearSelection();
    toast.success(`${ids.length} __resource__${ids.length === 1 ? "" : "s"} deleted`);
    await load(cursor);
  }

  const isEmpty = !loading && __resources__.length === 0;

  const createButton = (
    <Can code={createPerm}>
      <Button asChild>
        <Link href={`/${currentOrg.slug}/__resources__/new`}>New __resource__</Link>
      </Button>
    </Can>
  );

  return (
    <div>
      <PageHeader
        title="__Resources__"
        description="Generated by `pnpm gen resource __Resource__ --ui`."
        actions={isEmpty ? undefined : createButton}
      />
      {loading && __resources__.length === 0 ? (
        <__Resources__TableSkeleton />
      ) : (
        <DataTable
          columns={columns}
          data={__resources__}
          isLoading={loading}
          emptyState={
            <EmptyState
              icon={<Box />}
              title="No __resources__ yet"
              description="Create one to see the full CRUD slice."
              action={createButton}
            />
          }
          hasNextPage={Boolean(next)}
          hasPreviousPage={history.length > 0}
          onNextPage={() => {
            setHistory((entries) => [...entries, cursor]);
            setCursor(cursorFromUrl(next));
          }}
          onPreviousPage={() => {
            setHistory((entries) => {
              const nextHistory = entries.slice(0, -1);
              setCursor(entries.at(-1));
              return nextHistory;
            });
          }}
          bulkActions={
            canManage
              ? (ids, clearSelection) => (
                  <Button
                    variant="destructive"
                    size="sm"
                    onClick={() => setBulkPendingDelete({ ids, clearSelection })}
                  >
                    <Trash2 />
                    Delete
                  </Button>
                )
              : undefined
          }
        />
      )}

      <AlertDialog
        open={Boolean(rowPendingDelete)}
        onOpenChange={(open) => !open && setRowPendingDelete(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            {/* keel:insert row_delete_dialog_title */}
            <AlertDialogDescription>
              This cannot be undone. The __resource__ will be permanently removed.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => void onConfirmRowDelete()}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <AlertDialog
        open={Boolean(bulkPendingDelete)}
        onOpenChange={(open) => !open && setBulkPendingDelete(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              Delete {bulkPendingDelete?.ids.length} __resources__?
            </AlertDialogTitle>
            <AlertDialogDescription>
              This cannot be undone. All selected __resources__ will be permanently removed.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => void onConfirmBulkDelete()}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
