"use client";

import { Can } from "@/components/org/can";
import { applyFieldErrors } from "@/lib/api/form-error-mapper";
import { useOrgContext } from "@/lib/org/org-context";
import { Perm } from "@/lib/org/permissions";
import { delete__Resource__, get__Resource__, update__Resource__ } from "@/lib/__resources__/api";
import { zodResolver } from "@hookform/resolvers/zod";
import type { __Resource__Out } from "@keel/api-client";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  Button,
  FormField,
  // keel:if has_text
  FormTextarea,
  // keel:endif
  PageHeader,
  ResourceForm,
} from "@keel/ui";
import { Trash2 } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

// keel:insert choice_field_imports
import { __Resource__FormSkeleton } from "../_components/__resource__-form-skeleton";

const __resource__FormSchema = z.object({
  // keel:insert zod_shape
});
type __Resource__FormValues = z.infer<typeof __resource__FormSchema>;

/** `/[org]/__resources__/[id]` — generated by
 * `pnpm gen resource __Resource__ --ui`. */
export default function __Resource__DetailPage() {
  const router = useRouter();
  const params = useParams<{ org: string; id: string }>();
  const { currentOrg } = useOrgContext();
  const [__resource__, set__Resource__] = useState<__Resource__Out | null>(null);
  const [notFound, setNotFound] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const {
    // keel:if has_choice
    control,
    // keel:endif
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<__Resource__FormValues>({
    resolver: zodResolver(__resource__FormSchema),
    values: __resource__
      ? {
          // keel:insert edit_default_values
        }
      : undefined,
  });

  useEffect(() => {
    if (!currentOrg) return;
    let cancelled = false;
    get__Resource__(currentOrg.slug, params.id)
      .then((result) => {
        if (!cancelled) set__Resource__(result);
      })
      .catch(() => {
        if (!cancelled) setNotFound(true);
      });
    return () => {
      cancelled = true;
    };
  }, [currentOrg, params.id]);

  if (!currentOrg) return null;

  // keel:if crud_permissions
  const deletePerm = Perm.__RESOURCE___DELETE;
  // keel:endif
  // keel:if manage_permissions
  const deletePerm = Perm.__RESOURCES___MANAGE;
  // keel:endif
  // keel:insert display_value

  const breadcrumb = (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink asChild>
            <Link href={`/${currentOrg.slug}/__resources__`}>__Resources__</Link>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage>{__resource__ ? displayValue : "…"}</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  );

  if (notFound) {
    return (
      <div>
        <PageHeader breadcrumb={breadcrumb} title="__Resource__ not found" />
        <div className="rounded-lg border border-border p-6">
          <p className="text-sm text-muted-foreground">
            It doesn&apos;t exist, or it belongs to a different organisation.
          </p>
        </div>
      </div>
    );
  }

  if (!__resource__) {
    return (
      <div className="max-w-lg">
        <PageHeader breadcrumb={breadcrumb} title="…" />
        <__Resource__FormSkeleton />
      </div>
    );
  }

  async function onSubmit(values: __Resource__FormValues) {
    setFormError(null);
    try {
      const updated = await update__Resource__(currentOrg!.slug, params.id, values);
      set__Resource__(updated);
      toast.success("__Resource__ saved");
    } catch (error) {
      setFormError(applyFieldErrors(error, setError));
    }
  }

  async function onConfirmDelete() {
    await delete__Resource__(currentOrg!.slug, params.id);
    setDeleteOpen(false);
    // keel:insert delete_toast
    router.push(`/${currentOrg!.slug}/__resources__`);
  }

  return (
    <div className="max-w-lg">
      <PageHeader
        breadcrumb={breadcrumb}
        title={displayValue}
        actions={
          <Can code={deletePerm}>
            <Button variant="outline" onClick={() => setDeleteOpen(true)}>
              <Trash2 />
              Delete
            </Button>
          </Can>
        }
      />
      <ResourceForm
        onSubmit={handleSubmit(onSubmit)}
        formError={formError}
        submitLabel="Save changes"
        submittingLabel="Saving…"
        isSubmitting={isSubmitting}
      >
        {/* keel:insert form_fields */}
      </ResourceForm>

      <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            {/* keel:insert delete_dialog_title */}
            <AlertDialogDescription>
              This cannot be undone. The __resource__ will be permanently removed.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => void onConfirmDelete()}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
