import { Button, Text } from "@react-email/components";
import * as React from "react";
import { Layout } from "./Layout";

/**
 * Rendered to static HTML at build time (docs/plans/phase-5.md 5.5) with
 * these defaults left as literal ``{{TOKEN}}`` placeholders in the
 * output — Django substitutes them per-recipient at send time
 * (keel/notifications/emails.py). Do not pass real props when building;
 * the defaults *are* the template.
 *
 * Generated by `pnpm gen email __Resource__` (docs/plans/phase-19.md
 * 19.C) — the mechanical half only: props, their `{{TOKEN}}` defaults,
 * and (when one token looks like a URL) a button and a plain-text
 * fallback link. The body copy is judgement, left as a TODO — see
 * `packages/emails/templates/invitation.tsx` for the shape.
 */
export function __Resource__Email(props: {
  // keel:insert token_props
}) {
  // keel:insert token_defaults
  return (
    <Layout
      // keel:insert preview_prop
      // keel:insert heading_prop
    >
      {/* TODO: write the body copy. */}
      <Text>TODO — replace this line.</Text>
      // keel:insert cta_block
    </Layout>
  );
}

export default __Resource__Email;
